#pragma once

#include <Arduino.h>

#define DETECTOR_SERIAL_BAUD 115200

// Must match firmware/include/app_config.h.
// If the firmware sender is connected to a router, the detector must listen on
// the same Wi-Fi channel printed by the firmware as "sender ready ... channel=N".
// Leave 0 to keep the ESP32 default channel; set 1..13 when needed.
#ifndef ESPNOW_WIFI_CHANNEL
#define ESPNOW_WIFI_CHANNEL 0
#endif
#define ESPNOW_FRAME_MAGIC 0x49434546UL
#define ESPNOW_HELLO_MAGIC 0x49434548UL
#define ESPNOW_CHANNEL_HOP_INTERVAL_MS 120
#define ESPNOW_FRAME_CHUNK_BYTES 190

// Maximum JPEG frame accepted over ESP-NOW. Stored dynamically in PSRAM/heap,
// not in .dram0.bss, so large values do not overflow the linker DRAM region.
#define MAX_IMAGE_SIZE_BYTES (220 * 1024)
#define MAX_ESPNOW_FRAME_CHUNKS ((MAX_IMAGE_SIZE_BYTES + ESPNOW_FRAME_CHUNK_BYTES - 1) / ESPNOW_FRAME_CHUNK_BYTES)

// Must match the FOMO model generated by the Python training pipeline.
#define MODEL_INPUT_SIZE 96
#define MODEL_GRID_SIZE 12
#define MODEL_CLASS_COUNT 3
#define MODEL_CONFIDENCE_THRESHOLD 0.70f
#define MODEL_TENSOR_ARENA_BYTES (90 * 1024)

// Raw RGB888 fallback dimensions. JPEG frames are decoded dynamically.
#define RAW_SRC_W 96
#define RAW_SRC_H 96
