; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s3eye]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
board_build.partitions = partitions.csv
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 8MB
build_flags = 
	-DBOARD_HAS_PSRAM
	-DCAMERA_MODEL_ESP32S3_EYE
	-DCORE_DEBUG_LEVEL=3
lib_deps = 
	bblanchon/ArduinoJson@^7.0.0
	adafruit/Adafruit_VL53L0X@^1.2.5
	adafruit/Adafruit SSD1306@^2.5.17
	adafruit/Adafruit GFX Library@^1.12.6
	adafruit/Adafruit SH110X@^2.1.14
